CREATE DATABASE kratos;
GRANT ALL PRIVILEGES ON DATABASE kratos TO postgres;

CREATE DATABASE hydra;
GRANT ALL PRIVILEGES ON DATABASE hydra TO postgres;

CREATE DATABASE keto;
GRANT ALL PRIVILEGES ON DATABASE keto TO postgres;
